language: java
sudo: false
git:
  depth: 1
  submodules: true
before_install:
  - wget http://build.georchestra.org/m2.tar
  - tar xvf m2.tar -C ~ > /dev/null
cache:
  directories:
    - $HOME/.m2
notifications:
  irc:
    channels:
      - irc.freenode.net#georchestra
    template:
      - "%{repository}#%{build_number} (%{branch}) %{message} %{build_url}"
install: mvn install -DskipTests -P-all,travis
script: mvn integration-test -P-all,travis
addons:
  apt:
    packages:
      - ant
      - ant-optional
      - python-virtualenv
      - python-pip
